# Generated by Django 4.0.4 on 2022-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(choices=[('dance', 'Dance'), ('music', 'Music'), ('reading', 'Reading')], default='dance', max_length=255),
        ),
    ]
