# Generated by Django 4.0.4 on 2022-05-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='female', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(default='dance', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
